import streamlit as st
from scan_activity import install_scan_activity

st.set_page_config(page_title="PipsGo RS Scanner", page_icon=":material/query_stats:", layout="wide", initial_sidebar_state="expanded")

st.markdown("""
<style>
@import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap');
:root{--bg:#090b0d;--panel:#0e1213;--panel2:#141918;--line:#29302f;--soft:#202625;--text:#eef2f0;--muted:#707a77;--muted2:#525b59;--green:#48d39a;--amber:#e8b84f;--red:#ed7180}
*{box-sizing:border-box}html,body,[class*="css"]{font-family:Inter,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}
.stApp{background:var(--bg);color:var(--text)}.block-container{max-width:none;padding:0 1.45rem 2.25rem}
[data-testid="stHeader"]{background:var(--bg);border-bottom:1px solid var(--soft);height:2.8rem}[data-testid="stToolbar"]{display:none}
[data-testid="stSidebar"]{background:#0b0f10;border-right:1px solid var(--line);min-width:185px;max-width:185px}[data-testid="stSidebar"]>div:first-child{padding:1.05rem .72rem .8rem}
.sidebar-brand{padding:.1rem .5rem 1.45rem;font-size:1rem;font-weight:700;letter-spacing:.28em;color:var(--text)}.sidebar-brand span{color:var(--green)}
.sidebar-kicker{padding:0 .5rem .7rem;color:var(--muted2);font-size:.58rem;letter-spacing:.08em}.sidebar-section{padding:.9rem .5rem .42rem;color:var(--muted2);font-size:.56rem;letter-spacing:.18em;text-transform:uppercase}
[data-testid="stSidebarNav"]{padding:0 .1rem}[data-testid="stSidebarNav"] ul{gap:.22rem}[data-testid="stSidebarNav"] li a{border-radius:5px;color:#727b79;padding:.58rem .55rem;font-size:.78rem;font-weight:500}[data-testid="stSidebarNav"] li a:hover{background:#131918;color:var(--text)}[data-testid="stSidebarNav"] li a[aria-current="page"]{background:#18201f;color:var(--text);font-weight:600;box-shadow:inset 2px 0 0 var(--green)}[data-testid="stSidebarNav"] svg{width:.92rem;height:.92rem}.sidebar-bottom{position:fixed;bottom:.8rem;color:var(--muted2);font-size:.55rem;letter-spacing:.12em;padding-left:.5rem}
.app-topline{height:2.8rem;border-bottom:1px solid var(--line);display:flex;align-items:center;justify-content:space-between;margin:0 -1.45rem;padding:0 1.45rem;color:var(--muted2);font-size:.57rem;letter-spacing:.19em;text-transform:uppercase}.live-state{display:flex;align-items:center;gap:.4rem;color:#65706c;font-size:.57rem;letter-spacing:.11em}.live-dot{width:6px;height:6px;border-radius:50%;background:var(--green);box-shadow:0 0 8px rgba(72,211,154,.55)}
.page-head{display:flex;align-items:flex-end;justify-content:space-between;gap:1rem;padding:1.35rem 0 .95rem}.page-title{font-size:1.35rem;font-weight:650;letter-spacing:-.035em;line-height:1.1}.page-sub{color:var(--muted);font-size:.68rem;margin-top:.34rem}.header-actions{display:flex;align-items:center;gap:.45rem}
.control-bar{border-top:1px solid var(--line);border-bottom:1px solid var(--line);padding:.68rem 0 .55rem;margin-bottom:.85rem}.control-label{font-size:.57rem;color:var(--muted);letter-spacing:.08em;text-transform:uppercase;margin-bottom:.18rem}.control-help{font-size:.57rem;color:var(--muted2);margin-top:-.18rem}[data-testid="stSlider"]{margin-top:-.15rem}[data-testid="stCheckbox"] label p{font-size:.72rem;color:#cbd1cf}[data-testid="stNumberInput"] label p,[data-testid="stSelectbox"] label p,[data-testid="stTextInput"] label p{font-size:.62rem;color:var(--muted)}
.stButton>button,.stDownloadButton>button{border:1px solid var(--line);background:transparent;color:#b8c0bd;border-radius:5px;min-height:2rem;height:2rem;padding:.2rem .7rem;font-size:.68rem;font-weight:550;box-shadow:none}.stButton>button:hover,.stDownloadButton>button:hover{border-color:#46504d;background:#151a19;color:var(--text)}.header-actions .stButton>button{height:2.1rem;min-height:2.1rem}.header-actions .primary-action button{background:var(--green);border-color:var(--green);color:#07110d;font-weight:700}.header-actions .primary-action button:hover{background:#63dfa9;border-color:#63dfa9;color:#07110d}.header-actions .icon-action button{width:2.1rem;padding:0}
.status-card{border:1px solid var(--line);background:var(--panel);min-height:100%;padding:0}.status-head{padding:.68rem .72rem;border-bottom:1px solid var(--line);font-size:.56rem;color:var(--muted);letter-spacing:.16em;text-transform:uppercase}.status-state{display:flex;align-items:center;gap:.38rem;padding:.62rem .72rem;border-bottom:1px solid var(--line);font-size:.7rem;font-weight:600}.status-state .state-dot{width:6px;height:6px;border-radius:50%;background:var(--green)}.status-item{padding:.62rem .72rem;border-bottom:1px solid var(--soft)}.status-item:last-child{border-bottom:0}.status-label{font-size:.53rem;color:var(--muted2);letter-spacing:.12em;text-transform:uppercase}.status-value{font-size:.73rem;font-weight:600;margin-top:.18rem;color:#d9dfdd}.status-value.strong{color:var(--green)}.status-value.warn{color:var(--amber)}
.leader-strip{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));border-top:1px solid var(--line);border-bottom:1px solid var(--line);margin-bottom:.85rem}.leader-item{padding:.65rem .75rem;border-right:1px solid var(--line)}.leader-item:last-child{border-right:0}.leader-top{display:flex;align-items:center;justify-content:space-between}.leader-rank{font-size:.55rem;color:var(--muted2);letter-spacing:.08em}.leader-score{font-size:1.1rem;font-weight:650;color:var(--green)}.leader-name{font-size:.68rem;font-weight:600;margin-top:.22rem;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.leader-meta{font-size:.55rem;color:var(--muted2);margin-top:.16rem}
.results-head{display:flex;align-items:center;justify-content:space-between;margin:.25rem 0 .5rem}.results-title{font-size:.58rem;color:var(--muted2);letter-spacing:.18em;text-transform:uppercase}.results-count{color:var(--green);margin-left:.35rem}.results-search{max-width:260px}[data-testid="stDataFrame"]{border:1px solid var(--line);border-radius:5px;overflow:hidden;background:var(--panel)}[data-testid="stDataFrame"] [role="columnheader"]{background:#141918!important;color:#747e7b!important;font-size:.59rem!important;letter-spacing:.08em;text-transform:uppercase}[data-testid="stDataFrame"] [role="gridcell"]{font-size:.66rem!important}.table-action-row{display:flex;align-items:center;gap:.35rem;margin-top:.4rem}.table-foot{font-size:.56rem;color:var(--muted2);margin-top:.42rem}.legend{font-size:.56rem;color:var(--muted2);padding:.55rem 0;border-top:1px solid var(--soft);margin-top:.65rem}.dot{display:inline-block;width:6px;height:6px;border-radius:50%;margin:0 .25rem 0 .65rem}.dot:first-child{margin-left:0}.empty-state{border:1px dashed var(--line);padding:1.8rem;text-align:center;margin-top:1rem;color:var(--muted)}.empty-title{font-size:.78rem;color:#cdd4d1;font-weight:600}.empty-sub{font-size:.62rem;margin-top:.3rem}
[data-testid="stExpander"]{border:1px solid var(--line);border-radius:5px;background:var(--panel);margin-top:.75rem}[data-testid="stExpander"] summary{font-size:.62rem;color:#9aa39f}[data-testid="stProgress"]{margin:.25rem 0}.stAlert{border-radius:5px;font-size:.68rem}.footer{color:var(--muted2);font-size:.55rem;border-top:1px solid var(--soft);padding-top:.7rem;margin-top:.85rem}
@media(max-width:1100px){[data-testid="stSidebar"]{min-width:165px;max-width:165px}.block-container{padding-left:1rem;padding-right:1rem}.app-topline{margin-left:-1rem;margin-right:-1rem;padding-left:1rem;padding-right:1rem}.page-head{align-items:flex-start;flex-direction:column}.header-actions{width:100%}.header-actions .stButton{flex:1}}
@media(max-width:780px){[data-testid="stSidebar"]{min-width:0;max-width:none}.block-container{padding:0 .65rem 1.5rem}.app-topline{margin-left:-.65rem;margin-right:-.65rem;padding-left:.65rem;padding-right:.65rem}.leader-strip{grid-template-columns:1fr}.leader-item{border-right:0;border-bottom:1px solid var(--line)}.leader-item:last-child{border-bottom:0}.results-head{align-items:flex-start;gap:.45rem;flex-direction:column}.results-search{max-width:none;width:100%}}
</style>
""", unsafe_allow_html=True)

install_scan_activity()

index_page = st.Page("pages/index_rs.py", title="Index RS", icon=":material/leaderboard:", url_path="index-rs", default=True)
stock_page = st.Page("pages/stock_rs.py", title="Stock RS + Technical", icon=":material/query_stats:", url_path="stock-rs")

with st.sidebar:
    st.markdown('<div class="sidebar-brand"><span>PIPS</span>GOX</div>', unsafe_allow_html=True)
    st.markdown('<div class="sidebar-kicker">Market scanners</div>', unsafe_allow_html=True)
    st.markdown('<div class="sidebar-section">Scanners</div>', unsafe_allow_html=True)
    st.markdown('<div class="sidebar-section" style="margin-top:1.1rem">Saved screens</div>', unsafe_allow_html=True)
    st.markdown('<div class="sidebar-bottom">NSE · DAILY</div>', unsafe_allow_html=True)

pg = st.navigation([index_page, stock_page], position="sidebar")
pg.run()
